/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    BulkActions: typeof import('./src/components/inventory/BulkActions.vue')['default']
    CredentialLogin: typeof import('./src/components/auth/CredentialLogin.vue')['default']
    ItemTable: typeof import('./src/components/inventory/ItemTable.vue')['default']
    MoveItemsDialog: typeof import('./src/components/storage/MoveItemsDialog.vue')['default']
    OperationProgress: typeof import('./src/components/inventory/OperationProgress.vue')['default']
    RenameDialog: typeof import('./src/components/storage/RenameDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SavedAccountList: typeof import('./src/components/auth/SavedAccountList.vue')['default']
    StorageUnitCard: typeof import('./src/components/inventory/StorageUnitCard.vue')['default']
    ThemeToggle: typeof import('./src/components/common/ThemeToggle.vue')['default']
    TitleBar: typeof import('./src/components/layout/TitleBar.vue')['default']
    ToastContainer: typeof import('./src/components/common/ToastContainer.vue')['default']
    UApp: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UCheckbox: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UDropdownMenu: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UInput: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UProgress: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Progress.vue')['default']
  }
}
